# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
