## Automatically generated by odin - do not edit
.odin_model_determ <- odin:::odin_c_class("odin_model_determ", list(get_internal = "odin_model_determ_get_internal", finalise = "odin_model_determ_finalise", create = "odin_model_determ_create", initmod_desolve = "odin_model_determ_initmod_desolve", contents = "odin_model_determ_contents", set_user = "odin_model_determ_set_user", metadata = "odin_model_determ_metadata", initial_conditions = "odin_model_determ_initial_conditions", rhs = "odin_model_determ_rhs", rhs_dde = "odin_model_determ_rhs_dde", rhs_r = "odin_model_determ_rhs_r"), c("age_per", "agec", "amplitudes_phases", "Beta_hm_1", "Beta_mh_1", "BG_FOI", "deathrt", "Delta_season", "DeltaBase", "DT", "eip_mean", "eip_season", "Epsilon", "incub", "inf_per", "init_I1", "init_R1", "init_S", "Kappa", "Kc_season", "Mwt_cv", "Mwt_mean", "N_eq", "na", "Nb", "nn", "NP", "nu", "Omega", "phi1", "pi", "propMwtControl", "propTransGlobal", "propTransNN", "rho1", "Rm", "Sigma", "TimeMwtControlOff", "TimeMwtControlOn", "vacc_child_age", "vacc_child_coverage", "vacc_child_starttime", "vacc_child_stoptime", "vacc_cu_age", "vacc_cu_coverage", "vacc_cu_rndtime", "Wb_cyto", "Wb_fF", "Wb_fM", "Wb_introduration", "Wb_introlevel", "Wb_introtime", "Wb_mat", "Wb_relinf1", "Wb_relsusc1", "YL"), list(discrete = TRUE, has_array = TRUE, has_output = TRUE, has_user = TRUE, has_delay = FALSE, has_interpolate = FALSE, has_stochastic = FALSE, has_include = FALSE, initial_time_dependent = TRUE), "ZikaModel", "odin/odin_model_determ.json", TRUE)
odin_model_determ <- function (age_per, agec, amplitudes_phases, Beta_hm_1, Beta_mh_1,
    BG_FOI, deathrt, Delta_season, DeltaBase, DT, eip_mean, eip_season,
    Epsilon, incub, inf_per, init_I1, init_R1, init_S, Kappa,
    Kc_season, Mwt_cv, Mwt_mean, N_eq, na, Nb, nn, NP, nu, Omega,
    phi1, pi, propMwtControl, propTransGlobal, propTransNN, rho1,
    Rm, Sigma, TimeMwtControlOff, TimeMwtControlOn, vacc_child_age,
    vacc_child_coverage, vacc_child_starttime, vacc_child_stoptime,
    vacc_cu_age, vacc_cu_coverage, vacc_cu_rndtime, Wb_cyto,
    Wb_fF, Wb_fM, Wb_introduration, Wb_introlevel, Wb_introtime,
    Wb_mat, Wb_relinf1, Wb_relsusc1, YL, user = list(age_per = age_per,
        agec = agec, amplitudes_phases = amplitudes_phases, Beta_hm_1 = Beta_hm_1,
        Beta_mh_1 = Beta_mh_1, BG_FOI = BG_FOI, deathrt = deathrt,
        Delta_season = Delta_season, DeltaBase = DeltaBase, DT = DT,
        eip_mean = eip_mean, eip_season = eip_season, Epsilon = Epsilon,
        incub = incub, inf_per = inf_per, init_I1 = init_I1,
        init_R1 = init_R1, init_S = init_S, Kappa = Kappa, Kc_season = Kc_season,
        Mwt_cv = Mwt_cv, Mwt_mean = Mwt_mean, N_eq = N_eq, na = na,
        Nb = Nb, nn = nn, NP = NP, nu = nu, Omega = Omega, phi1 = phi1,
        pi = pi, propMwtControl = propMwtControl, propTransGlobal = propTransGlobal,
        propTransNN = propTransNN, rho1 = rho1, Rm = Rm, Sigma = Sigma,
        TimeMwtControlOff = TimeMwtControlOff, TimeMwtControlOn = TimeMwtControlOn,
        vacc_child_age = vacc_child_age, vacc_child_coverage = vacc_child_coverage,
        vacc_child_starttime = vacc_child_starttime, vacc_child_stoptime = vacc_child_stoptime,
        vacc_cu_age = vacc_cu_age, vacc_cu_coverage = vacc_cu_coverage,
        vacc_cu_rndtime = vacc_cu_rndtime, Wb_cyto = Wb_cyto,
        Wb_fF = Wb_fF, Wb_fM = Wb_fM, Wb_introduration = Wb_introduration,
        Wb_introlevel = Wb_introlevel, Wb_introtime = Wb_introtime,
        Wb_mat = Wb_mat, Wb_relinf1 = Wb_relinf1, Wb_relsusc1 = Wb_relsusc1,
        YL = YL), unused_user_action = NULL)
{
    .odin_model_determ$new(user, unused_user_action)
}
class(odin_model_determ) <- "odin_generator"
attr(odin_model_determ, "ir") <- .odin_model_determ$public_fields$ir
.odin_model_stoch <- odin:::odin_c_class("odin_model_stoch", list(get_internal = "odin_model_stoch_get_internal", finalise = "odin_model_stoch_finalise", create = "odin_model_stoch_create", initmod_desolve = "odin_model_stoch_initmod_desolve", contents = "odin_model_stoch_contents", set_user = "odin_model_stoch_set_user", metadata = "odin_model_stoch_metadata", initial_conditions = "odin_model_stoch_initial_conditions", rhs = "odin_model_stoch_rhs", rhs_dde = "odin_model_stoch_rhs_dde", rhs_r = "odin_model_stoch_rhs_r"), c("age_per", "agec", "Beta_hm_1", "Beta_mh_1", "BG_FOI", "deathrt", "Delta_season", "DeltaBase", "DT", "eip_mean", "eip_season", "Epsilon", "incub", "inf_per", "init_I1", "init_R1", "init_S", "Kappa", "Kc_season", "Mwt", "Mwt_mean", "N_eq", "na", "Nb", "nn", "NP", "nu", "Omega", "phi1", "pi", "propMwtControl", "propTransGlobal", "propTransNN", "rho1", "Rm", "season_amp", "season_phase", "Sigma", "TimeMwtControlOff", "TimeMwtControlOn", "Wb_cyto", "Wb_fF", "Wb_mat", "Wb_relinf1", "YL"), list(discrete = TRUE, has_array = TRUE, has_output = TRUE, has_user = TRUE, has_delay = FALSE, has_interpolate = FALSE, has_stochastic = TRUE, has_include = FALSE, initial_time_dependent = TRUE), "ZikaModel", "odin/odin_model_stoch.json", TRUE)
odin_model_stoch <- function (age_per, agec, Beta_hm_1, Beta_mh_1, BG_FOI, deathrt,
    Delta_season, DeltaBase, DT, eip_mean, eip_season, Epsilon,
    incub, inf_per, init_I1, init_R1, init_S, Kappa, Kc_season,
    Mwt, Mwt_mean, N_eq, na, Nb, nn, NP, nu, Omega, phi1, pi,
    propMwtControl, propTransGlobal, propTransNN, rho1, Rm, season_amp,
    season_phase, Sigma, TimeMwtControlOff, TimeMwtControlOn,
    Wb_cyto, Wb_fF, Wb_mat, Wb_relinf1, YL, user = list(age_per = age_per,
        agec = agec, Beta_hm_1 = Beta_hm_1, Beta_mh_1 = Beta_mh_1,
        BG_FOI = BG_FOI, deathrt = deathrt, Delta_season = Delta_season,
        DeltaBase = DeltaBase, DT = DT, eip_mean = eip_mean,
        eip_season = eip_season, Epsilon = Epsilon, incub = incub,
        inf_per = inf_per, init_I1 = init_I1, init_R1 = init_R1,
        init_S = init_S, Kappa = Kappa, Kc_season = Kc_season,
        Mwt = Mwt, Mwt_mean = Mwt_mean, N_eq = N_eq, na = na,
        Nb = Nb, nn = nn, NP = NP, nu = nu, Omega = Omega, phi1 = phi1,
        pi = pi, propMwtControl = propMwtControl, propTransGlobal = propTransGlobal,
        propTransNN = propTransNN, rho1 = rho1, Rm = Rm, season_amp = season_amp,
        season_phase = season_phase, Sigma = Sigma, TimeMwtControlOff = TimeMwtControlOff,
        TimeMwtControlOn = TimeMwtControlOn, Wb_cyto = Wb_cyto,
        Wb_fF = Wb_fF, Wb_mat = Wb_mat, Wb_relinf1 = Wb_relinf1,
        YL = YL), unused_user_action = NULL)
{
    .odin_model_stoch$new(user, unused_user_action)
}
class(odin_model_stoch) <- "odin_generator"
attr(odin_model_stoch, "ir") <- .odin_model_stoch$public_fields$ir
